// File: app/fighters/data.js
export const fighters = [
  // ==========================
  // 1. PRO FIGHTERS
  // ==========================
  { 
    id: "riedzwan-norsyahmie", 
    name: "Riedzwan Norsyahmie Daud", 
    nickname: "The Golden Shin", 
    team: "66 Unicorn x S Inn Malay", 
    coach: "Maman Ajmain", 
    managerContact: "60109417666", 
    record: "14W - 4L (10 KO)", 
    category: "Pro", 
    age: "24",
    weight: "61 KG", 
    height: "172 CM",
    stance: "Orthodox",
    image: "/syahmie.jpeg", 
    gender: "Male",
    achievements: ["One Championship promising fighter", "Multiple KO Artist", "SUKMA 2022 Bronze", "National Athlete", "Fury Redemption 2025 Champion", "contender in One Championship 2025"],
    bio: "Known as 'The Golden Shin', Riedzwan is Sabah's most dangerous striker. A One Championship contract winner with a terrifying 71% KO ratio, he combines elite technical skills with devastating power."
  },
  { 
    id: "mohammad-syahrizan", 
    name: "Mohammad Syahrizan", 
    nickname: "Sleeping Touch", 
    team: "D'Sha Muayfit Tawau", 
    coach: "Sharon Andrea Gerald", 
    managerContact: "60165525785", 
    record: "Pro: 3W - 0L | Am: 25W - 2L", 
    category: "Pro", 
    age: "20",
    weight: "51-54 KG", 
    height: "162 CM",
    stance: "Orthodox",
    image: "/syarizan.jpeg", 
    gender: "Male",
    achievements: ["Sukma 2024 Champion", "Sabah Games 2023 Gold", "Sabah Games 2025 Gold"],
    bio: "Known as 'Sleeping Touch' for his deceptive finishing ability. An undefeated Pro (3-0) and reigning Sukma 2024 Champion, Syahrizan is one of the most decorated young prospects in the state."
  },
  { 
    id: "mohammad-arizan", 
    name: "Mohammad Arizan Kamaron", 
    nickname: "Arizan", 
    team: "D'Sha Muayfit Tawau", 
    coach: "Sharon Andrea Gerald", 
    managerContact: "60165525785", 
    record: "Pro: 4W - 2L | Am: 12W - 2L", 
    category: "Pro", 
    age: "24",
    weight: "51 KG", 
    height: "157 CM",
    stance: "Orthodox",
    image: "/arizan.jpeg", 
    gender: "Male",
    achievements: ["Sabah Games 2019 Bronze", "Sabah Pro Fighter"],
    bio: "Arizan is a seasoned competitor from Tawau with a solid professional winning record. He is known for his grit and high-volume striking, consistently performing at the state level."
  },
  { 
    id: "hasbullah-sanmin", 
    name: "Mohammad Hasbullah Sanmin", 
    nickname: "D. Garagas", 
    team: "Garagas Fight Team", 
    coach: "Head Coach", 
    managerContact: "601126695935", 
    record: "14W - 4L", 
    category: "Pro", 
    age: "28",
    weight: "55-57 KG", 
    height: "162 CM",
    stance: "Orthodox",
    image: "/hasbullah.jpeg", 
    gender: "Male",
    achievements: ["Veteran Pro Fighter", "Garagas Team Leader"],
    bio: "A true veteran of the sport with 14 professional wins, Hasbullah 'D. Garagas' Sanmin is the heart of the Garagas Fight Team. He brings years of ring experience and high fight IQ to every bout."
  },
  { 
    id: "eva-anastasia-warren", 
    name: "Eva Anastasia Warren", 
    nickname: "Eva", 
    team: "Tambuakar Martial Arts Papar", 
    coach: "Coach Rozaimy", 
    managerContact: "60198008093", 
    record: "5W - 3L", 
    category: "Pro", 
    age: "20",
    weight: "48 KG", 
    height: "159 CM",
    stance: "Orthodox",
    image: "/eva.jpeg", 
    gender: "Female",
    achievements: ["33rd SEA Games Silver Medalist", "IFMA Asian 2025 Silver", "SUKMA 2024 Gold", "SAGA 2025 Best Boxer"],
    bio: "Eva is Sabah's premier female fighter. A SEA Games Silver Medalist and SUKMA Champion, she is an aggressive technician who consistently performs on the international stage."
  },
  { 
    id: "muhammad-rahmad-combat", 
    name: "Muhammad Rahmad", 
    nickname: "Mad Kool", 
    team: "66 Unicorn (Sandakan)", 
    coach: "Maman Ajmain", 
    managerContact: "60109417666", 
    record: "4W - 0L (Undefeated)", 
    category: "Pro", 
    age: "22",
    weight: "45-48 KG", 
    height: "163 CM",
    stance: "Orthodox",
    image: "/rahmad-madkool.jpeg", 
    gender: "Male",
    achievements: ["Undefeated Pro", "SUKMA 2024 Silver Medalist", "Sandakan Pride"],
    bio: "An undefeated prospect (4-0) and SUKMA Silver Medalist, 'Mad Kool' Rahmad is Sandakan's pride. His speed and agility make him a nightmare matchup for anyone in the division."
  },
  { 
    id: "shah-aryan", 
    name: "Shah Aryan B. Shahzam", 
    nickname: "The Killer Prince", 
    team: "Revolution Combat Gym", 
    coach: "Dhillon Tahing", 
    managerContact: "60168013530", 
    record: "4W - 2L", 
    category: "Pro", 
    age: "24",
    weight: "51 KG", 
    height: "159 CM",
    stance: "Southpaw",
    image: "/shah.jpeg", 
    gender: "Male",
    achievements: ["National Champion", "Ex Sukma Sabah Fighter", "Experienced Pro", "SUKMA 2022 Silver Medalist", "2023 Max Muaythai, Thailand 1-0"],
    bio: "Known as 'The Killer Prince', Shah Aryan is a dangerous Southpaw from Revolution Combat Gym. A former National Champion, he brings excitement to every fight with his aggressive style."
  },
  { 
    id: "kallens-barthez", 
    name: "Kallens Barthez Jafili", 
    nickname: "Showtime", 
    team: "Team Karabaw Tamparuli", 
    coach: "Kenny Jafili", 
    managerContact: "601126237463", 
    record: "3W - 1L", 
    category: "Pro", 
    age: "23",
    weight: "60 KG", 
    height: "173 CM",
    stance: "Orthodox",
    image: "/kallens.jpeg", 
    gender: "Male",
    achievements: ["Signed with Byon Indonesia", "Ex Sukma Sabah Fighter", "Fan Favorite"],
    bio: "Kallens 'Showtime' lives up to his name. A crowd pleaser referring to himself as 'ORANG GILA SABAH', he recently signed with Byon Indonesia to take his high-energy style international."
  },
  { 
    id: "iman-madley", 
    name: "Iman Madley", 
    nickname: "Payakchai", 
    team: "Revolution Combat Gym", 
    coach: "Dhillon Tahing", 
    managerContact: "60168013530", 
    record: "3W - 2L", 
    category: "Pro", 
    age: "20",
    weight: "51 KG", 
    height: "166 CM",
    stance: "Orthodox",
    image: "/iman.jpeg", 
    gender: "Male",
    achievements: ["SAGA 2023 Silver Medalist", "State Champion", "SAGA 2025 Fighter"],
    bio: "Iman 'Payakchai' brings a traditional Thai style to his fights. A State Champion and SAGA Silver Medalist, he is a dangerous operator in the clinch."
  },
  { 
    id: "areen-khan", 
    name: "Areen Khan Shahzam", 
    nickname: "King Dede", 
    team: "Revolution Combat Gym", 
    coach: "Dhillon Tahing", 
    managerContact: "60168013530", 
    record: "3W - 3L", 
    category: "Pro", 
    age: "25",
    weight: "49 KG", 
    height: "159 CM",
    stance: "Orthodox",
    image: "/areen.jpg", 
    gender: "Male",
    achievements: ["SAGA 2019 Gold Medalist", "State Champion", "Ex Sukma Fighter"],
    bio: "Areen 'King Dede' Khan is a former SAGA Gold Medalist and State Champion. Fighting in the lighter weight classes, he is known for his speed and technical exchanges."
  },
  { 
    id: "tu-sim-bee", 
    name: "Tu Sim Bee", 
    nickname: "Sim Bee", 
    team: "Uppercross Muay Thai Club", 
    coach: "Sin Yee", 
    managerContact: "601116043075", 
    record: "3W - 3L", 
    category: "Pro", 
    age: "30",
    weight: "43-46 KG", 
    height: "155 CM",
    stance: "Orthodox",
    image: "/tusimbee.jpeg", 
    video: "/tusimbee.mp4",
    gender: "Female",
    achievements: ["Women's Division Standout"],
    bio: "Sim Bee is a tough competitor in the women's division. Representing Uppercross, she has faced strong opposition and continues to improve her game."
  },
  { 
    id: "sammy-aaagaras", 
    name: "Yong Feng Yue", 
    nickname: "Sammy", 
    team: "Aaagaras Muay", 
    coach: "Ranjit Singh", 
    managerContact: "60168288773", 
    record: "2W - 2L | BAMC GOLD", 
    category: "Pro", 
    age: "18",
    weight: "45 KG", 
    height: "N/A",
    stance: "Orthodox",
    image: "/sammy.jpeg", 
    gender: "Female",
    achievements: ["BAMC Gold Medalist", "SAGA 2025 Gold Medalist", "State Champion"],
    bio: "Sammy is a standout young talent. A Gold Medalist at both BAMC and SAGA 2025, she has proven herself as a technically sound fighter from the Aaagaras stable."
  },
  { 
    id: "rifhan-wazizi", 
    name: "Rifhan Wazizi Bin Irwan", 
    nickname: "Hemo", 
    team: "Hemo Fight Camp Kudat", 
    coach: "Neo", 
    managerContact: "60102120870", 
    record: "1W - 1L", 
    category: "Pro", 
    age: "19",
    weight: "51 KG", 
    height: "160 CM",
    stance: "Orthodox",
    image: "/rifhan.jpeg", 
    gender: "Male",
    achievements: ["Kudat Champion"],
    bio: "Representing the northern region of Kudat, Rifhan 'Hemo' brings a rugged and tough style to the ring. He is a local champion known for his durability."
  },
  { 
    id: "aliff-iqbal", 
    name: "Mohammad Aliff Iqbal", 
    nickname: "Iqbal", 
    team: "Karabaw Tamparuli", 
    coach: "Kenny Jafili", 
    managerContact: "01126237463", 
    record: "1W - 0L", 
    category: "Pro", 
    age: "23",
    weight: "54 KG", 
    height: "167 CM",
    stance: "Orthodox",
    image: "/iqbal.jpeg", 
    gender: "Male",
    achievements: ["Pro Debut Winner"],
    bio: "Another strong fighter from the Karabaw stable, Aliff Iqbal successfully transitioned to the pro ranks with a win. He possesses excellent reach for his weight class."
  },
  { 
    id: "milan-peneh", 
    name: "Milan Peneh", 
    nickname: "Milan", 
    team: "Stallone Fitness", 
    coach: "Mohd Fadzirllah", 
    managerContact: "60169774685", 
    record: "1W - 0L", 
    category: "Pro", 
    age: "25",
    weight: "65 KG", 
    height: "167 CM",
    stance: "Orthodox",
    image: "/milan.jpeg", 
    gender: "Male",
    achievements: ["Undefeated Debut"],
    bio: "Milan Peneh made a statement with his professional debut. Fighting out of Stallone Fitness, he brings heavy hands and durability."
  },
  { 
    id: "jasper-lee", 
    name: "Jasper Lee", 
    nickname: "Jasper", 
    team: "Uppercross Muay Thai Club", 
    coach: "Sin Yee", 
    managerContact: "601116043075", 
    record: "1W - 0L", 
    category: "Pro", 
    age: "22",
    weight: "54 KG", 
    height: "168 CM",
    stance: "Orthodox",
    image: "/jasper.jpeg", 
    gender: "Male",
    achievements: ["Debut Winner"],
    bio: "Jasper Lee is a promising talent from Uppercross. He started his pro career with a win and looks to climb the ranks with his precision striking."
  },
  { 
    id: "johnathan-chung", 
    name: "Johnathan Chung", 
    nickname: "Chung", 
    team: "Uppercross Muay Thai Club", 
    coach: "Sin Yee", 
    managerContact: "601116043075", 
    record: "1W - 0L", 
    category: "Pro", 
    age: "21",
    weight: "54 KG", 
    height: "165 CM",
    stance: "Orthodox",
    image: "/johnathan.jpeg", 
    gender: "Male",
    achievements: ["Debut Winner"],
    bio: "Another winner from the Uppercross team, Johnathan Chung showed great potential in his first professional outing."
  },
  { 
    id: "awang-muhammad-hazimie", 
    name: "Awang Muhammad Hazimie", 
    nickname: "Montoi", 
    team: "Kelab Muaythai Montoi", 
    coach: "Jonathan / Awang Handra", 
    managerContact: "60178117118", 
    record: "Pro: 0-1 | Am: 24-5", 
    category: "Pro", 
    age: "22",
    weight: "63-64 KG", 
    height: "169 CM",
    stance: "Orthodox",
    image: "/montoi.jpeg", 
    gender: "Male",
    achievements: ["2024 Pra Sukma Gold", "2023 SAGA Gold", "2022 SEA Games Athlete"],
    bio: "An amateur veteran with 24 wins, 'Montoi' is a SEA Games athlete and Gold Medalist making the tough transition to the professional league."
  },
  { 
    id: "syafiq-ezuan", 
    name: "Syafiq Ezuan", 
    nickname: "Syafiq", 
    team: "Karabaw Tamparuli", 
    coach: "Kenny Jafili", 
    managerContact: "01126237463", 
    record: "Pro: 0-1 | Am: 18-5", 
    category: "Pro", 
    age: "23",
    weight: "51 KG", 
    height: "163 CM",
    stance: "Orthodox",
    image: "/syafiq.jpeg", 
    gender: "Male",
    achievements: ["Sabah Inter-Club Champion", "SAGA 2023 Gold Medalist", "Ex Sabah Sukma Fighter"],
    bio: "Syafiq is a relentless pressure fighter from Tamparuli. With extensive amateur experience (18 wins) and a SAGA Gold medal, he is known for his cardio and inability to take a step backward."
  },
  { 
    id: "irick-richard", 
    name: "Irick Richard Teo", 
    nickname: "Irick", 
    team: "Revolution Combat Gym", 
    coach: "Dhillon Tahing", 
    managerContact: "60168013530", 
    record: "0W - 1L", 
    category: "Pro", 
    age: "23",
    weight: "54 KG", 
    height: "168 CM",
    stance: "Orthodox",
    image: "/irick.jpeg", 
    gender: "Male",
    achievements: ["Pro Fighter"],
    bio: "Irick is a dedicated fighter from Revolution Combat Gym. Despite a tough start, his training ethic and determination make him one to watch."
  },
  { 
    id: "efron-jaidin", 
    name: "Efron Jaidin", 
    nickname: "Efron", 
    team: "AWP Martial Art Academy", 
    coach: "Addyana June Adangku", 
    managerContact: "601152599024", 
    record: "0W - 2L", 
    category: "Pro", 
    age: "21",
    weight: "57-60 KG", 
    height: "162 CM",
    stance: "Orthodox",
    image: "/efron.jpeg", 
    gender: "Male",
    achievements: ["SAGA 2025 Gold Medalist", "SAGA 2023 Gold Medalist", "SUKMA 2024 Bronze Medalist"],
    bio: "Fighting out of AWP Martial Art Academy, Efron is a resilient fighter. A two-time SAGA Gold Medalist and SUKMA Bronze winner, he has a strong amateur pedigree."
  },

  // ==========================
  // 2. PRO & MUAYSPORTS (HYBRIDS)
  // ==========================
  { 
    id: "evyanka-qistina", 
    name: "Evyanka Qistina Ady", 
    nickname: "Pumpkin", 
    team: "D'Sha Muayfit Tawau", 
    coach: "Sharon Andrea Gerald", 
    managerContact: "60165525785", 
    record: "Pro: 0-1 | Am: 14-2", 
    category: "Pro & Muaysports", 
    age: "15",
    weight: "45-48 KG", 
    height: "157 CM",
    stance: "Orthodox",
    image: "/pumpkin.jpeg", 
    gender: "Female",
    achievements: ["Young Pro Debutant", "Amateur Champion"],
    bio: "Don't let the nickname 'Pumpkin' fool you. Evyanka is a fierce young competitor with 14 amateur wins. At just 15 years old, she is already testing herself in the professional ranks."
  },
  { 
    id: "asyraf-danial-combat", 
    name: "Asyraf Danial", 
    nickname: "Acapski", 
    team: "Revolution Combat Gym", 
    coach: "Dhillon Tahing", 
    managerContact: "60168013530", 
    record: "Pro: 1-2 | Muaysports: 11-5", 
    category: "Pro & Muaysports", 
    age: "20",
    weight: "67-73 KG", 
    height: "178 CM",
    stance: "Orthodox",
    image: "/asyraf-danial.jpeg", 
    gender: "Male",
    achievements: ["3x IFMA World Champion", "2024 IFMA Greece Gold", "2025 ASIAN Vietnam Silver"],
    bio: "Acapski is a world-class athlete. A 3x IFMA World Champion, he is equally dangerous in combat as he is skilled in the cultural arts of Muay Thai."
  },
  { 
    id: "kerry-dryan-hybrid", 
    name: "Kerry Dryan Jafili", 
    nickname: "Dryan", 
    team: "Team Karabaw Tamparuli", 
    coach: "Kenny Jafili", 
    managerContact: "601126237463", 
    record: "Pro: 0-1 | Am: 23-5 | BAMC GOLD", 
    category: "Pro & Muaysports", 
    age: "18",
    weight: "71 KG", 
    height: "178 CM",
    stance: "Orthodox",
    image: "/kerry.jpeg", 
    gender: "Male",
    achievements: ["BAMC Gold Medalist", "Sabah SUKMA Fighter 2024"],
    bio: "Kerry 'Dryan' is a tall and rangy fighter with massive amateur experience (23 wins). He is a BAMC Gold Medalist and a key member of Team Karabaw."
  },
  { 
    id: "eddli-llyod-frederik", 
    name: "Eddli Llyod Angello Frederik", 
    nickname: "Eddli", 
    team: "Revolution Combat Gym", 
    coach: "Dhillon Tahing", 
    managerContact: "60168013530", 
    record: "Pro: 2-0-0 | Am: 4-6", 
    category: "Pro & Muaysports", 
    age: "20",
    weight: "57 KG", 
    height: "165 CM",
    stance: "Orthodox",
    image: "/eddli.jpeg", 
    gender: "Male",
    achievements: ["Undefeated Pro Record", "Rising Star"],
    bio: "Eddli 'The Silencer' is a rising talent. Undefeated in his professional career, he is known for his calm demeanor and precise striking."
  },
  { 
    id: "muhammad-hezric", 
    name: "Muhammad Hezric", 
    nickname: "Sugar Boy", 
    team: "Naga Kinabalu", 
    coach: "Airudin", 
    managerContact: "60128188958", 
    record: "Semi Pro: 2-1 | Muaysports: 7-5", 
    category: "Pro & Muaysports", 
    age: "22",
    weight: "60 KG", 
    height: "N/A",
    stance: "Orthodox",
    image: "/hezric.jpeg", 
    gender: "Male",
    achievements: ["Semi-Pro Winner"],
    bio: "Hezric 'Sugar Boy' has a slick style. With a winning semi-pro record, he represents Naga Kinabalu with flair and technical prowess."
  },
  { 
    id: "muhammad-izack-dsha", 
    name: "Muhammad Izack Bin Devid", 
    nickname: "Izack", 
    team: "D'Sha Muayfit Tawau", 
    coach: "Sharon Andrea Gerald", 
    managerContact: "601119020943", 
    record: "1W-0L | BAMC GOLD", 
    category: "Pro & Muaysports", 
    age: "16",
    weight: "55 KG", 
    height: "168 CM",
    stance: "Orthodox",
    image: "/izack.jpeg", 
    gender: "Male",
    achievements: ["2025 National Gold", "2025 ASEAN Gold", "2025 SAGA Gold"],
    bio: "Izack is a golden talent from Tawau. Dominating the 2025 season with National, ASEAN, and SAGA Gold medals, he is one of the hottest prospects in the region."
  },
  { 
    id: "stacy-poong-combat", 
    name: "Stacy Poong Dai Hee", 
    nickname: "Stacy", 
    team: "AWP Martial Art Academy", 
    coach: "Addyana June Adangku", 
    managerContact: "601152599024", 
    record: "Pro: 0-1 | Am: 8-4 | SUKMA GOLD", 
    category: "Pro & Muaysports", 
    age: "20",
    weight: "50-55 KG", 
    height: "157 CM",
    stance: "Orthodox",
    image: "/stacy-poong.jpeg", 
    gender: "Female",
    achievements: ["SUKMA Gold Medalist"],
    bio: "Stacy Poong is a SUKMA Gold Medalist, proving her elite status in the national amateur scene. She fights with high volume and great conditioning."
  },
  { 
    id: "fazreen-ezra", 
    name: "Fazreen", 
    nickname: "Ezra", 
    team: "Revolution Combat Gym", 
    coach: "Dhillon Tahing", 
    managerContact: "60168013530", 
    record: "Pro: 0-1 | Muaysports: 5-4", 
    category: "Pro & Muaysports", 
    age: "19",
    weight: "54 KG", 
    height: "170 CM",
    stance: "Orthodox",
    image: "/fazreen-ezra.jpeg", 
    gender: "Male",
    achievements: ["Hybrid Athlete", "SAGA 2025 Silver Medalist"],
    bio: "Fazreen 'Ezra' is a versatile fighter from Revolution Combat Gym, competing in both professional bouts and muaysports tournaments. He is a SAGA 2025 Silver Medalist."
  },

  // ==========================
  // 3. MUAYSPORTS
  // ==========================
  { 
    id: "mb-khairul", 
    name: "Mb Mohd Khairul Ariffin", 
    nickname: "MB", 
    team: "Stallone Fitness", 
    coach: "Mohd Fadzirllah", 
    managerContact: "60169774685", 
    record: "9W - 1L | BAMC GOLD", 
    category: "Muaysports", 
    age: "20",
    weight: "65 KG", 
    height: "178 CM",
    stance: "Orthodox",
    image: "/mbkhairul.jpeg", 
    gender: "Male",
    achievements: ["BAMC Gold Medalist", "Dominant Record"],
    bio: "With an impressive 9-1 record, MB is a dominant force in the amateur scene. His BAMC Gold medal cements his status as a top contender."
  },
  { 
    id: "adib-syazwan", 
    name: "Adib Syazwan", 
    nickname: "Adib", 
    team: "Revolution Combat Muaythai Gym", 
    coach: "Dhillon Tahing", 
    managerContact: "0168013530", 
    record: "Amateur: 6-4", 
    category: "Muaysports", 
    age: "18",
    weight: "67 KG", 
    height: "178 CM",
    stance: "Orthodox",
    image: "/adib.jpeg", 
    gender: "Male",
    achievements: ["Amateur Contender"],
    bio: "Adib is a strong amateur competitor with a winning record. He uses his height and reach effectively in muaysports competitions."
  },
  { 
    id: "lim-zhi-hui", 
    name: "Lim Zhi Hui", 
    nickname: "Zhi Hui", 
    team: "Aaagaras Muay", 
    coach: "Ranjit Singh", 
    managerContact: "0168288773", 
    record: "Amateur: 6-3", 
    category: "Muaysports", 
    age: "19",
    weight: "54 KG", 
    height: "165 CM",
    stance: "Orthodox",
    image: "/limzhihui.jpeg", 
    gender: "Female",
    achievements: ["Active Competitor", "SAGA 2025 Silver Medalist"],
    bio: "Lim Zhi Hui is a dedicated active competitor from Aaagaras Muay. A SAGA 2025 Silver Medalist, she consistently participates in local tournaments."
  },
  { 
    id: "johanizamsyah-phantom", 
    name: "Johanizamsyah Bin Johanis", 
    nickname: "The Phantom", 
    team: "Xmuayfitness", 
    coach: "Coach Song", 
    managerContact: "0142827907", 
    record: "Gold Medalist", 
    category: "Muaysports", 
    age: "19",
    weight: "54-57 KG", 
    height: "N/A",
    stance: "Orthodox",
    image: "/phantom.jpeg", 
    gender: "Male",
    achievements: ["Gold Medalist"],
    bio: "'The Phantom' is a gold medalist from Xmuayfitness, known for his elusive style and counter-attacking ability."
  },
  { 
    id: "johanitasyah-johns", 
    name: "Johanitasyah Binti Johanis", 
    nickname: "TasyahJohns", 
    team: "Xmuayfitness", 
    coach: "Coach Song", 
    managerContact: "0142827907", 
    record: "Gold Medalist", 
    category: "Muaysports", 
    age: "21",
    weight: "48-51 KG", 
    height: "N/A",
    stance: "Orthodox",
    image: "/tasyah.jpeg", 
    gender: "Female",
    achievements: ["Gold Medalist"],
    bio: "Tasyah is a gold medalist representing Xmuayfitness. She is a skilled female athlete with a bright future."
  },
  { 
    id: "davien-jhudiel-combat", 
    name: "Davien Jhudiel Mobilik Elliot", 
    nickname: "Davien", 
    team: "Monster Muaythai", 
    coach: "Jonathan Quan", 
    managerContact: "0178117118", 
    record: "SMC Gold 2025", 
    category: "Muaysports", 
    age: "19",
    weight: "57 KG", 
    height: "N/A", 
    stance: "Orthodox",
    image: "/davien.jpeg", 
    gender: "Male",
    achievements: ["SMC KB 2025 Gold Combat"],
    bio: "Davien is a standout from Monster Muaythai. Winning Gold at SMC KB 2025, he has proven his combat capability."
  },

  // ==========================
  // 4. U17
  // ==========================
  { 
    id: "hectlyor-rawing", 
    name: "Hectlyor Rawing", 
    nickname: "Hectlyor", 
    team: "D'Sha Muayfit Tawau", 
    coach: "Sharon Andrea Gerald", 
    managerContact: "60142048368", 
    record: "Muaysports: 10W - 4L", 
    category: "U17", 
    age: "15", 
    weight: "45-48 KG", 
    height: "164 CM", 
    stance: "Orthodox",
    image: "/hector.jpeg", 
    gender: "Male",
    achievements: ["Kebangsaan 2025 Athlete", "ASEAN Games 2025 Athlete"],
    bio: "Fighting out of D'Sha Muayfit Tawau, Hectlyor 'Hector' Rawing is a rising teen prospect. With experience at the National and ASEAN levels in 2025, he is building a strong foundation for his future."
  },
  { 
    id: "ersyahbbel-asharie", 
    name: "Ersyahbbel Asharie", 
    nickname: "Abel", 
    team: "D'Sha Muayfit Tawau", 
    coach: "Sharon Andrea Gerald", 
    managerContact: "60165525785", 
    record: "Amateur: 9W - 4L", 
    category: "U17", 
    age: "16",
    weight: "60-63 KG", 
    height: "172 CM",
    stance: "Orthodox",
    image: "/abel.jpeg", 
    gender: "Male",
    achievements: ["SabahGames 2025", "ASEAN 2025", "Kebangsaan 2025"],
    bio: "Abel is a rising star in the youth division. Standing tall at 172cm, he had a breakout year in 2025, competing as a standout at the SAGA, ASEAN, and National games."
  },
  { 
    id: "nick-nynell-letto", 
    name: "Nick Nynell Arletto", 
    nickname: "Letto", 
    team: "Revolution Muaythai Kota Marudu", 
    coach: "Mexron James", 
    managerContact: "60192588268", 
    record: "10W - 8L", 
    category: "U17", 
    age: "16",
    weight: "42-45 KG", 
    height: "N/A",
    stance: "Orthodox",
    image: "/nick-nynell.jpeg", 
    gender: "Male",
    achievements: ["Kota Marudu Young Gun"],
    bio: "Nick 'Letto' is a highly active youth fighter from Kota Marudu. With nearly 20 fights under his belt, he has experience beyond his years."
  },
  { 
    id: "hafizi-montoi", 
    name: "Awang Muhammad Hafizi", 
    nickname: "Fizi", 
    team: "Kelab Muaythai Montoi", 
    coach: "Awang Handra / Montoi", 
    managerContact: "0178117118", 
    record: "Amatur Record: 7W - 3L", 
    category: "U17", 
    age: "15",
    weight: "48-51 KG", 
    height: "N/A",
    stance: "Orthodox",
    image: "/fizi.jpeg", 
    gender: "Male",
    achievements: ["SMC 2025 Silver", "Rookie Gold", "SAGA Tawau Silver"],
    bio: "Fizi is a talented youth fighter from the Montoi clan. With a solid winning record and multiple medals, he is following in the footsteps of his seniors."
  },
  { 
    id: "jaethan-jonathan-combat", 
    name: "Jaethan Jonathan Quan", 
    nickname: "Sumoboy", 
    team: "Monster Muaythai", 
    coach: "Jonathan Quan", 
    managerContact: "0178117118", 
    record: "Amateur: 5W - 6L", 
    category: "U17", 
    age: "15",
    weight: "54-57 KG", 
    height: "160 CM",
    stance: "Orthodox",
    image: "/jaethancombat.jpeg", 
    gender: "Male",
    achievements: ["SMC KB 2025 Gold", "D1 2025 Gold", "IFMA YWC Representative"],
    bio: "Jaethan 'Sumoboy' is a youth phenom. An IFMA representative and multiple Gold medalist (SMC, D1), he is the future of the sport."
  },
  { 
    id: "rozana-laila", 
    name: "Rozana Laila Rammy", 
    nickname: "Laila", 
    team: "AWP Martial Art Academy", 
    coach: "Addyana June Adangku", 
    managerContact: "601152599024", 
    record: "5W - 6L", 
    category: "U17", 
    age: "16",
    weight: "45-48 KG", 
    height: "159 CM",
    stance: "Orthodox",
    image: "/rozana-laila.jpeg", 
    gender: "Female",
    achievements: ["2025 Silver SAGA Tawau"],
    bio: "Laila is a tough female youth fighter from AWP. A SAGA Silver medalist, she competes with heart and skill."
  },
  { 
    id: "noor-azmani", 
    name: "Noor Azmani Bin Noorzain", 
    nickname: "Azmani", 
    team: "Revolution Combat Gym", 
    coach: "Dhillon Tahing", 
    managerContact: "60168013530", 
    record: "4W - 6L", 
    category: "U17", 
    age: "17",
    weight: "57-60 KG", 
    height: "171 CM",
    stance: "Orthodox",
    image: "/noor-azmani.jpeg", 
    gender: "Male",
    achievements: ["Youth Prospect"],
    bio: "Azmani is a developing youth fighter from Revolution Combat Gym. He has good height for his weight and is improving with every fight."
  },

  // ==========================
  // 5. ARTS (Gold Medals Prestige Sort)
  // ==========================
  { 
    id: "asyraf-danial-arts", 
    name: "Asyraf Danial", 
    nickname: "Acapski", 
    team: "Revolution Combat Gym", 
    coach: "Dhillon Tahing", 
    managerContact: "60168013530", 
    record: "IFMA 3x Gold", 
    category: "Arts", 
    division: "Wai Kru and Maimuay",
    age: "20", 
    weight: "N/A", 
    height: "178 CM",
    image: "/asyraf-danial-arts.jpeg", 
    gender: "Male",
    achievements: ["IFMA THAILAND, TURKEY, GREECE Gold", "IFMA ASIAN GAME VIETNAM Silver", " SEA GAMES 2025 BRONZE"],
    bio: "In the Arts division, Acapski is a legend. His multiple IFMA Gold Medals prove he is one of the best Wai Kru practitioners in the world."
  },
  { 
    id: "jaethan-jonathan-arts", 
    name: "Jaethan Jonathan Quan", 
    nickname: "Sumoboy", 
    team: "Monster Muaythai", 
    coach: "Jonathan Quan", 
    managerContact: "0178117118", 
    record: "IFMA World Gold", 
    category: "Arts", 
    division: "Wai Kru and Maimuay",
    age: "16", 
    weight: "N/A", 
    height: "160 CM",
    image: "/jaethanart.jpeg", 
    gender: "Male",
    achievements: ["IFMA Abu Dhabi Gold", "IFMA Bangkok Silver", "Asian Youth Bronze"],
    bio: "A young prodigy in the Arts. Jaethan has conquered the world stage with an IFMA Gold in Abu Dhabi and continues to rack up international medals."
  },
  { 
    id: "auryelle-xzandra", 
    name: "Auryelle Xzandra Bobby", 
    nickname: "Aury", 
    team: "AWP Martial Art Academy", 
    coach: "Addyana June Adangku", 
    managerContact: "601152599024", 
    record: "Waikru Gold", 
    category: "Arts", 
    division: "Wai Kru", 
    age: "16", 
    weight: "N/A", 
    height: "N/A",
    image: "/auryelle.jpeg", 
    gender: "Female",
    achievements: ["2025 Silver Asian Youth Games", "Gold ASEAN Game KL", "Gold SAGA Games Tawau"],
    bio: "Aury is a highly decorated Arts athlete. With Golds at ASEAN and SAGA games, and a Silver at Asian Youth, she is a top-tier performer."
  },
  { 
    id: "davien-jhudiel-arts", 
    name: "Davien Jhudiel Mobilik Elliot", 
    nickname: "Davien", 
    team: "Monster Muaythai", 
    coach: "Jonathan Quan", 
    managerContact: "0178117118", 
    record: "National Gold", 
    category: "Arts", 
    division: "Maimuay",
    age: "19", 
    weight: "N/A", 
    height: "N/A",
    image: "/davien.jpeg", 
    gender: "Male",
    achievements: ["National Pra Sukma Gold Maimuay", "SAGA Gold"],
    bio: "Davien excels in the cultural arts as well. He is a National Gold medalist in Maimuay, showcasing the traditional techniques of the sport."
  },
  { 
    id: "ariesya-dania", 
    name: "Ariesya Dania", 
    nickname: "Ari", 
    team: "Revolution Combat Gym", 
    coach: "Dhillon Tahing", 
    managerContact: "60168013530", 
    record: "Waikru Gold", 
    category: "Arts", 
    division: "Wai Kru",
    age: "17", 
    weight: "N/A", 
    height: "N/A",
    image: "/ariesya-dania.jpg", 
    gender: "Female",
    achievements: ["National Best Cultural Athlete 2025", "Asian Youth Game, Bahrain Bronze", "World IFMA  Youth 2024 Thailand Silver Medalist", "National Senior 2025 Gold Medalist", "SAGA 2025 Silver Medalist"],
    bio: "Ari is a specialist in Wai Kru. Recognized as a National Best Cultural Athlete, she preserves the beautiful traditions of Muay Thai."
  },
  { 
    id: "bless-alexis-angus", 
    name: "Bless Alexis Angus", 
    nickname: "Bless", 
    team: "Monster Muaythai", 
    coach: "Jonathan Quan", 
    managerContact: "0178117118", 
    record: "National Gold", 
    category: "Arts", 
    division: "Wai kru and Maimuay",
    age: "16", 
    weight: "N/A", 
    height: "N/A",
    image: "/bless.jpeg", 
    gender: "Female",
    achievements: ["Pra Sukma Gold Mix", "National Gold Duo"],
    bio: "Bless is a synchronized specialist. Winning National Gold in Duo events, she showcases impeccable timing and teamwork."
  },
  { 
    id: "stacy-poong-arts", 
    name: "Stacy Poong Dai Hee", 
    nickname: "Stacy", 
    team: "AWP Martial Art Academy", 
    coach: "Addyana June Adangku", 
    managerContact: "601152599024", 
    record: "Culture Gold", 
    category: "Arts", 
    division: "Maimuay",
    age: "20", 
    weight: "N/A", 
    height: "157 CM",
    image: "/stacy-arts.jpeg", 
    gender: "Female",
    achievements: ["2025 Gold Culture Heritage"],
    bio: "Stacy brings her winning mentality to the Arts division as well, securing Gold in Cultural Heritage events."
  },
  { 
    id: "addy-ardryqa", 
    name: "Addy Ardryqa Bin Arman", 
    nickname: "Addy", 
    team: "AWP Martial Art Academy", 
    coach: "Addyana June Adangku", 
    managerContact: "601152599024", 
    record: "Waikru Gold", 
    category: "Arts", 
    division: "Wai Kru",
    age: "15", 
    weight: "N/A", 
    height: "N/A",
    image: "/addy-ardryqa.jpeg", 
    gender: "Male",
    achievements: ["Gold ASEAN KL", "Gold Culture Heritage"],
    bio: "Addy is a top-tier Arts competitor from AWP. With Gold medals at the ASEAN level, he is a master of the Wai Kru form."
  },
  { 
    id: "bethany-lai", 
    name: "Bethany Lai Yun Yunn", 
    nickname: "Bethany", 
    team: "Monster Muaythai", 
    coach: "Jonathan Quan", 
    managerContact: "0178117118", 
    record: "Asian Youth Bronze", 
    category: "Arts", 
    division: "Wai kru and Maimuay",
    age: "16", 
    weight: "N/A", 
    height: "N/A",
    image: "/bethany.jpeg", 
    gender: "Female",
    achievements: ["Asian Youth Bahrain 2025 Bronze", "Pra Sukma Gold"],
    bio: "Bethany brings grace and precision to the Arts division. An Asian Youth Bronze medalist and Pra Sukma Gold winner from Monster Muaythai."
  }
];